In [ ]:
pip install esm

Collecting esm
  Downloading esm-3.2.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: torch>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from esm) (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from esm) (0.25.0+cu128)
Collecting torchtext (from esm)
  Downloading torchtext-0.18.0-cp312-cp312-manylinux1_x86_64.whl.metadata (7.9 kB)
Collecting transformers<4.48.2 (from esm)
  Downloading transformers-4.48.1-py3-none-any.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from esm) (7.34.0)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from esm) (0.8.2)
Collecting biotite>=1.0.0 (from esm)
  Downloading biotite-1.6.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting msgpack-numpy (from esm)
  Downloading msgpack_numpy-0.4.8-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting biopython (from esm)
  Downloading biopython-1.86-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from esm) (1.6.1)
Requirement already satisfied: brotli in /usr/local/lib/python3.12/dist-packages (from esm) (1.2.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.12/dist-packages (from esm) (25.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from esm) (2.2.2)
Requirement already satisfied: cloudpathlib in /usr/local/lib/python3.12/dist-packages (from esm) (0.23.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from esm) (0.28.1)
Requirement already satisfied: tenacity in /usr/local/lib/python3.12/dist-packages (from esm) (9.1.4)
Collecting zstd (from esm)
  Downloading zstd-1.5.7.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata (29 kB)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (from esm) (7.7.1)
Collecting py3dmol (from esm)
  Downloading py3dmol-2.5.4-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting pydssp (from esm)
  Downloading pydssp-0.9.1-py3-none-any.whl.metadata (4.9 kB)
Collecting boto3 (from esm)
  Downloading boto3-1.42.59-py3-none-any.whl.metadata (6.7 kB)
Collecting pygtrie (from esm)
  Downloading pygtrie-2.5.0-py3-none-any.whl.metadata (7.5 kB)
Collecting dna_features_viewer (from esm)
  Downloading dna_features_viewer-3.1.5-py3-none-any.whl.metadata (2.1 kB)
Collecting biotraj<2.0,>=1.0 (from biotite>=1.0.0->esm)
  Downloading biotraj-1.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (32 kB)
Requirement already satisfied: msgpack>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from biotite>=1.0.0->esm) (1.1.2)
Requirement already satisfied: networkx>=2.0 in /usr/local/lib/python3.12/dist-packages (from biotite>=1.0.0->esm) (3.6.1)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from biotite>=1.0.0->esm) (2.0.2)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from biotite>=1.0.0->esm) (26.0)
Requirement already satisfied: requests>=2.12 in /usr/local/lib/python3.12/dist-packages (from biotite>=1.0.0->esm) (2.32.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2.0->esm) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.2.0->esm) (1.3.5)
Collecting huggingface-hub<1.0,>=0.24.0 (from transformers<4.48.2->esm)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers<4.48.2->esm) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<4.48.2->esm) (2025.11.3)
Collecting tokenizers<0.22,>=0.21 (from transformers<4.48.2->esm)
  Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers<4.48.2->esm) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers<4.48.2->esm) (4.67.3)
Collecting botocore<1.43.0,>=1.42.59 (from boto3->esm)
  Downloading botocore-1.42.59-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->esm)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3->esm)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: matplotlib>=3 in /usr/local/lib/python3.12/dist-packages (from dna_features_viewer->esm) (3.10.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->esm) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx->esm) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->esm) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx->esm) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->esm) (0.16.0)
Collecting jedi>=0.16 (from ipython->esm)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->esm) (4.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->esm) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->esm) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->esm) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->esm) (3.0.16)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->esm) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->esm) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->esm) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->esm) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->esm) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->esm) (3.6.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision->esm) (11.3.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.43.0,>=1.42.59->boto3->esm) (2.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers<4.48.2->esm) (1.3.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (7.4.9)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets->esm) (6.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->esm) (0.8.6)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3->dna_features_viewer->esm) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3->dna_features_viewer->esm) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3->dna_features_viewer->esm) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3->dna_features_viewer->esm) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3->dna_features_viewer->esm) (3.3.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->esm) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->esm) (0.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->esm) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.12->biotite>=1.0.0->esm) (3.4.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.2.0->esm) (1.3.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->esm) (6.5.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.2.0->esm) (3.0.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->esm) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->esm) (5.9.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (25.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (7.17.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.24.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (1.3.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->esm) (4.9.2)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (4.26.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (1.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.30.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2.14.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (2.8.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (3.0)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->esm) (0.5.4)

In [ ]:
import pandas as pd
import torch
import os
import numpy as np
from esm.models.esmc import ESMC
from esm.sdk.api import ESMProtein, LogitsConfig

In [ ]:
columns = [
    "pdb_id",
    "receptor_chain",
    "resolution",
    "binding_site_code",
    "ligand_id",
    "ligand_chain",
    "ligand_serial_number",
    "binding_residues_pdb",
    "binding_residues_seq",
    "catalytic_residues_pdb",
    "catalytic_residues_seq",
    "ec_number",
    "go_terms",
    "binding_affinity_manual",
    "binding_affinity_moad",
    "binding_affinity_pdbbind",
    "binding_affinity_bindingdb",
    "uniprot_id",
    "pubmed_id",
    "ligand_residue_seq_number",
    "sequence"
]

df = pd.read_csv("BioLiP_nr.txt.gz", sep="\t", names=columns, header=None)

df = df[['pdb_id', 'receptor_chain', 'resolution', 'ligand_id', 'binding_residues_seq','sequence']]

print(df.shape)
print(df.ligand_id.value_counts())
df.head()

/tmp/ipykernel_513/973534019.py:25: DtypeWarning: Columns (13,14,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("BioLiP_nr.txt.gz", sep="\t", names=columns, header=None)

(86458, 6)
ligand_id
rna      9528
ZN       8255
CLA      7354
CA       6176
dna      4231
         ...
4CH         1
YS4         1
RRY         1
A1D6H       1
G50         1
Name: count, Length: 6019, dtype: int64

,pdb_id,receptor_chain,resolution,ligand_id,binding_residues_seq,sequence
0,10mh,A,2.55,dna,I86 Q90 R209 G236 Q237 G256 G257,MIEIKDKQLTGLRFIDLFAGLGGFRLALESCGAECVYSNEWDKYAQ...
1,10mh,A,2.55,dna,F79 C81 S87 E119 R165 R228 Q237 R240 I249 T250...,MIEIKDKQLTGLRFIDLFAGLGGFRLALESCGAECVYSNEWDKYAQ...
2,10mh,A,2.55,SAH,F18 A19 G20 L21 G23 E40 W41 D60 N304 S305,MIEIKDKQLTGLRFIDLFAGLGGFRLALESCGAECVYSNEWDKYAQ...
3,11as,A,2.50,ASN,D43 A71 Q113 Y215 S248 R252,AYIAKQRQISFVKSHFSRQLEERLGLIEVQAPILSRVGDGTQDNLS...
4,11ba,A,2.06,UPA,K41 V43 N44 T45 N67 Q69 N71 A109 H119 F120,KESAAAKFERQHMDSGNSPSSSSNYCNLMMCCRKMTQGKCKPVNTF...

In [ ]:
df = df[df['binding_residues_seq'].notna()]
df = df[df['ligand_id'].notna()]

to_remove = {
    # Metal ions
    "ZN", "CA", "MG", "MN", "FE", "FE2", "CU", "CU1", "CO", "NI", "CD", "HG", "MN3",
    "CL", "AG", "LA", "YB", "RB", "PB", "SE", "AU", "BR", "IOD",
    # Nucleic acids
    "RNA", "DNA", "PEPTIDE",
    # Crystallization artifacts
    "SO4", "GOL", "EDO", "PO4", "ACT", "BME", "MPD", "FMT", "ACE", "DMS", "PGE",
    "EOH", "TRS", "IMD", "PGW", "C8E", "C2E",
    # Free amino acids
    "GLY", "ALA", "VAL", "LEU", "ILE", "PRO", "PHE", "TRP", "SER", "THR", "CYS",
    "MET", "ASN", "GLN", "ASP", "GLU", "LYS", "ARG", "HIS", "TYR"
}

df_cleaned = df[~df["ligand_id"].str.upper().isin(to_remove)]
df_cleaned.reset_index(drop= True, inplace=True)
df_cleaned

,pdb_id,receptor_chain,resolution,ligand_id,binding_residues_seq,sequence
0,10mh,A,2.55,SAH,F18 A19 G20 L21 G23 E40 W41 D60 N304 S305,MIEIKDKQLTGLRFIDLFAGLGGFRLALESCGAECVYSNEWDKYAQ...
1,11ba,A,2.06,UPA,K41 V43 N44 T45 N67 Q69 N71 A109 H119 F120,KESAAAKFERQHMDSGNSPSSSSNYCNLMMCCRKMTQGKCKPVNTF...
2,13pk,A,2.50,ADP,G213 A214 K219 L311 P336 G338 V339 E341 G371 D...,EKKSINECDLKGKKVLIRVDFNVPVKNGKITNDYRIRSALPTLKKV...
3,155c,A,2.50,HEM,C15 C18 H19 I46 A47 Y54 G55 I58 W70 Y78 V79 K9...,NEGDAAKGEKEFNKCKACHMIQAPDGTDIKGGKTGPNLYGVVGRKI...
4,19hc,A,1.80,HEM,S8 A10 M16 F35 H37 H40 I44 C47 C50 H51 P56 V57...,AALEPTDSGAPSAIVMFPVGEKPNPKGAAMKPVVFNHLIHEKKIAD...
...,...,...,...,...,...,...
43983,9vf7,A,2.40,FMN,V17 N50 C51 R52 L54 Q55 V64 I71 L81 N83 N93 L9...,RDEIFRIAVETILAGVVITDAQLPDYPIVYCNPGFVQLTGYPSEEV...
43984,9vid,A,2.22,HEM,Y42 F43 H45 H58 K61 R82 L83 L86 H87 L91 N97 F9...,VLSMEDKSNVKAIWGKASGHLEEYGAEALERMFCAYPQTKIYFPHF...
43985,9vid,B,2.22,HEM,K38 F42 H44 F45 H63 V67 S70 L88 H92 F96 V98 N1...,ASFDAHERKFIVDLWAKVDVAQCGADALSRMLIVYPWKRRYFEHFG...
43986,9vmx,D,3.20,L9Q,R874 L875 F1213,ELVKGVYAKYWIYVCAGMFIVVSFAGRLVVYKIVYMFLFLLCLTLF...
43987,9vmx,D,3.20,L9Q,L1208 K1212 R1215,ELVKGVYAKYWIYVCAGMFIVVSFAGRLVVYKIVYMFLFLLCLTLF...

In [ ]:
df_cleaned['sequence_length (aa)'] = df_cleaned['sequence'].apply(lambda x: len(x))
df_cleaned = df_cleaned[df_cleaned['resolution'] <= 2.50]
df_cleaned = df_cleaned[(df_cleaned['sequence_length (aa)'] >= 150) & (df_cleaned['sequence_length (aa)'] <= 800)]
df_cleaned = df_cleaned.drop_duplicates(['pdb_id','ligand_id'])
df_cleaned.reset_index(drop=True, inplace=True)
df_cleaned

/tmp/ipykernel_513/3719118623.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['sequence_length (aa)'] = df_cleaned['sequence'].apply(lambda x: len(x))

,pdb_id,receptor_chain,resolution,ligand_id,binding_residues_seq,sequence,sequence_length (aa)
0,13pk,A,2.500,ADP,G213 A214 K219 L311 P336 G338 V339 E341 G371 D...,EKKSINECDLKGKKVLIRVDFNVPVKNGKITNDYRIRSALPTLKKV...,415
1,19hc,A,1.800,HEM,S8 A10 M16 F35 H37 H40 I44 C47 C50 H51 P56 V57...,AALEPTDSGAPSAIVMFPVGEKPNPKGAAMKPVVFNHLIHEKKIAD...,292
2,1a05,A,2.000,IPM,R95 R105 R133 Y140 D246,MKKIAIFAGDGIGPEIVAAARQVLDAVDQAAHLGLRCTEGLVGGAA...,357
3,1a0g,B,2.000,PMP,R50 K145 E177 S180 S181 G203 I204 T205 S240 T241,GYTLWNDQIVKDEEVKIDKEDRGYQFGDGVYEVVKVYNGEMFTVNE...,282
4,1a26,A,2.250,CNA,H165 M229 K242 L323 L324 Y325 E327,KSKLAKPIQDLIKMIFDVESMKKAMVEFEIDLQKMPLGKLSKRQIQ...,351
...,...,...,...,...,...,...,...
14564,9us4,B,1.950,AC1,T238 H334,AWTTTDFPAFTEEGTGRFISQKVVEKGTRPLQLNFDQQCWQPSGGI...,652
14565,9us4,B,1.950,GLC,H439 W480,AWTTTDFPAFTEEGTGRFISQKVVEKGTRPLQLNFDQQCWQPSGGI...,652
14566,9v14,A,0.930,42B,D12 C13 Y14 S121 N122 K152 E180 S181 H184,MQLTDFKALTFDCYGTLIDWETGIVNALQPLAKRTGKTFTSDELLE...,240
14567,9v59,A,2.175,GLC,M171 A174 R178,GTGFPFDPHYVEVLGERMHYVDVGPRDGTPVLFLHGNPTSSYVWRN...,462
14568,9v59,A,2.175,A1EQX,D102 E143 T144 F145 L157 Q161 V163 W167 T168 M...,GTGFPFDPHYVEVLGERMHYVDVGPRDGTPVLFLHGNPTSSYVWRN...,462

In [ ]:
rows = []

for index, row in df_cleaned.iterrows():
  binding_residues = set()

  for binding_residue in row['binding_residues_seq'].split():
    position = int(''.join(filter(str.isdigit, binding_residue)))
    binding_residues.add(position)

  for i, residue in enumerate(row['sequence']):
    rows.append({
        'pdb_id': row['pdb_id'],
        'receptor_chain': row['receptor_chain'],
        'ligand_id': row['ligand_id'],
        'position': i+1,
        'residue': residue,
        'isbinding': 1 if i+1 in binding_residues else 0,
        })

residue_df = pd.DataFrame(rows)

In [ ]:
residue_df

        pdb_id receptor_chain ligand_id  position residue  isbinding
0         13pk              A       ADP         1       E          0
1         13pk              A       ADP         2       K          0
2         13pk              A       ADP         3       K          0
3         13pk              A       ADP         4       S          0
4         13pk              A       ADP         5       I          0
...        ...            ...       ...       ...     ...        ...
5057166   9v59              A     A1EQX       458       T          0
5057167   9v59              A     A1EQX       459       L          0
5057168   9v59              A     A1EQX       460       E          0
5057169   9v59              A     A1EQX       461       I          0
5057170   9v59              A     A1EQX       462       S          0

[5057171 rows x 6 columns]

In [ ]:
client = ESMC.from_pretrained("esmc_300m").to("cuda")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

README.md: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

data/weights/esmc_300m_2024_12_v0.pth:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

In [ ]:
os.makedirs("embeddings_proteins2", exist_ok=True)

for _, entry in df_cleaned.iterrows():
    pdb_id    = entry["pdb_id"]
    chain     = entry["receptor_chain"]
    ligand    = entry["ligand_id"]

    unique_id = f"{pdb_id}_{chain}_{ligand}"
    save_path = f"embeddings_proteins2/{unique_id}.npy"

    if os.path.exists(save_path):
        continue

    seq = entry["sequence"]
    protein = ESMProtein(sequence=seq)
    protein_tensor = client.encode(protein)

    with torch.no_grad():
        output = client.logits(
            protein_tensor,
            LogitsConfig(sequence=True, return_embeddings=True)
        )

    embeddings = output.embeddings.squeeze(0).half().cpu().numpy()[1:-1, :]
    np.save(save_path, embeddings)

    del output, embeddings
    torch.cuda.empty_cache()

print("✅ All embeddings saved to disk")

✅ All embeddings saved to disk

In [ ]:
EMBEDDINGS_DIR = "embeddings_proteins2"
OUTPUT_DIR = "embedding_chunks2"
os.makedirs(OUTPUT_DIR, exist_ok=True)

for _, entry in df_cleaned.iterrows():
    pdb_id    = entry["pdb_id"]
    chain     = entry["receptor_chain"]
    ligand    = entry["ligand_id"]
    unique_id = f"{pdb_id}_{chain}_{ligand}"

    chunk_path = f"{OUTPUT_DIR}/{unique_id}.parquet"
    if os.path.exists(chunk_path):
        continue

    embeddings = np.load(f"{EMBEDDINGS_DIR}/{unique_id}.npy")

    meta = pd.DataFrame({
        "pdb_id":         pdb_id,
        "receptor_chain": chain,
        "ligand_id":      ligand,
        "position":       np.arange(1, len(embeddings) + 1)
    })

    esm_cols = pd.DataFrame(embeddings, columns=[f"esm_{i}" for i in range(embeddings.shape[1])])

    chunk_df = pd.concat([meta, esm_cols], axis=1)
    chunk_df.to_parquet(chunk_path, index=False)

    del embeddings, chunk_df, meta, esm_cols

print("✅ All chunks saved")

✅ All chunks saved

In [ ]:
embedding_df = pd.read_parquet(OUTPUT_DIR)
print(embedding_df.shape)
embedding_df

In [ ]:
df_merge = residue_df.merge(
    embedding_df,
    on=["pdb_id", "receptor_chain", "ligand_id", "position"],
    how="inner"
)

In [ ]:
df_merge

In [ ]:
"""
df_merge.to_parquet(
    "model_dataset.parquet",
    engine="pyarrow",
    compression="zstd"
)
"""

In [ ]:
# ESM helper class encapsulating the steps in this notebook to produce `df_merge`
import os
import numpy np
import pandas as pd
import torch
from typing import Optional
from esm.models.esmc import ESMC
from esm.sdk.api import ESMProtein, LogitsConfig


class ESM:
    """Encapsulate dataset loading, cleaning, embedding extraction (ESM), chunking and merging.

    Methods:
     - load_biolip: read raw BioLiP file
     - clean: filter and clean raw dataframe
     - make_residue_df: expand sequences into per-residue rows with isbinding label
     - init_client: load ESM model to device
     - compute_embeddings: encode sequences and save per-protein .npy embeddings
     - chunk_embeddings: turn saved .npy embeddings into per-protein parquet chunks with esm_ columns
     - load_embedding_df: read all chunk parquet files into a single dataframe
     - merge: merge residue dataframe with embedding dataframe -> df_merge
     - save: write final df_merge to parquet
     - run_all: convenience to run entire pipeline
    """

    def __init__(
        self,
        model_name: str = "esmc_300m",
        device: Optional[str] = None,
        embeddings_dir: str = "embeddings_proteins2",
        chunks_dir: str = "embedding_chunks2",
    ):
        self.model_name = model_name
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.embeddings_dir = embeddings_dir
        self.chunks_dir = chunks_dir
        self.client: Optional[ESMC] = None

    def load_biolip(self, path: str = "BioLiP_nr.txt.gz") -> pd.DataFrame:
        columns = [
            "pdb_id",
            "receptor_chain",
            "resolution",
            "binding_site_code",
            "ligand_id",
            "ligand_chain",
            "ligand_serial_number",
            "binding_residues_pdb",
            "binding_residues_seq",
            "catalytic_residues_pdb",
            "catalytic_residues_seq",
            "ec_number",
            "go_terms",
            "binding_affinity_manual",
            "binding_affinity_moad",
            "binding_affinity_pdbbind",
            "binding_affinity_bindingdb",
            "uniprot_id",
            "pubmed_id",
            "ligand_residue_seq_number",
            "sequence",
        ]

        df = pd.read_csv(path, sep="\t", names=columns, header=None)
        df = df[["pdb_id", "receptor_chain", "resolution", "ligand_id", "binding_residues_seq", "sequence"]]
        return df

    def clean(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df[df["binding_residues_seq"].notna()]
        df = df[df["ligand_id"].notna()]

        to_remove = {
            # Metal ions
            "ZN",
            "CA",
            "MG",
            "MN",
            "FE",
            "FE2",
            "CU",
            "CU1",
            "CO",
            "NI",
            "CD",
            "HG",
            "MN3",
            "CL",
            "AG",
            "LA",
            "YB",
            "RB",
            "PB",
            "SE",
            "AU",
            "BR",
            "IOD",
            # Nucleic acids
            "RNA",
            "DNA",
            "PEPTIDE",
            # Crystallization artifacts
            "SO4",
            "GOL",
            "EDO",
            "PO4",
            "ACT",
            "BME",
            "MPD",
            "FMT",
            "ACE",
            "DMS",
            "PGE",
            "EOH",
            "TRS",
            "IMD",
            "PGW",
            "C8E",
            "C2E",
            # Free amino acids
            "GLY",
            "ALA",
            "VAL",
            "LEU",
            "ILE",
            "PRO",
            "PHE",
            "TRP",
            "SER",
            "THR",
            "CYS",
            "MET",
            "ASN",
            "GLN",
            "ASP",
            "GLU",
            "LYS",
            "ARG",
            "HIS",
            "TYR",
        }

        df_cleaned = df[~df["ligand_id"].str.upper().isin(to_remove)].copy()
        df_cleaned.reset_index(drop=True, inplace=True)

        # compute sequence length and filter by resolution and length
        df_cleaned["sequence_length (aa)"] = df_cleaned["sequence"].apply(lambda x: len(x))
        df_cleaned = df_cleaned[df_cleaned["resolution"] <= 2.50]
        df_cleaned = df_cleaned[(df_cleaned["sequence_length (aa)"] >= 150) & (df_cleaned["sequence_length (aa)"] <= 800)]
        df_cleaned = df_cleaned.drop_duplicates(["pdb_id", "ligand_id"])
        df_cleaned.reset_index(drop=True, inplace=True)

        return df_cleaned

    def make_residue_df(self, df_cleaned: pd.DataFrame) -> pd.DataFrame:
        rows = []
        for _, row in df_cleaned.iterrows():
            binding_residues = set()
            for binding_residue in row["binding_residues_seq"].split():
                position = int("".join(filter(str.isdigit, binding_residue)))
                binding_residues.add(position)

            for i, residue in enumerate(row["sequence"]):
                rows.append(
                    {
                        "pdb_id": row["pdb_id"],
                        "receptor_chain": row["receptor_chain"],
                        "ligand_id": row["ligand_id"],
                        "position": i + 1,
                        "residue": residue,
                        "isbinding": 1 if i + 1 in binding_residues else 0,
                    }
                )

        residue_df = pd.DataFrame(rows)
        return residue_df

    def init_client(self):
        if self.client is None:
            self.client = ESMC.from_pretrained(self.model_name).to(self.device)

    def compute_embeddings(self, df_cleaned: pd.DataFrame, force: bool = False):
        os.makedirs(self.embeddings_dir, exist_ok=True)
        self.init_client()

        for _, entry in df_cleaned.iterrows():
            pdb_id = entry["pdb_id"]
            chain = entry["receptor_chain"]
            ligand = entry["ligand_id"]

            unique_id = f"{pdb_id}_{chain}_{ligand}"
            save_path = os.path.join(self.embeddings_dir, f"{unique_id}.npy")

            if os.path.exists(save_path) and not force:
                continue

            seq = entry["sequence"]
            protein = ESMProtein(sequence=seq)
            protein_tensor = self.client.encode(protein)

            with torch.no_grad():
                output = self.client.logits(protein_tensor, LogitsConfig(sequence=True, return_embeddings=True))

            embeddings = output.embeddings.squeeze(0).half().cpu().numpy()[1:-1, :]
            np.save(save_path, embeddings)

            del output, embeddings
            torch.cuda.empty_cache()

        print("✅ All embeddings saved to disk")

    def chunk_embeddings(self, df_cleaned: pd.DataFrame, force: bool = False):
        os.makedirs(self.chunks_dir, exist_ok=True)

        for _, entry in df_cleaned.iterrows():
            pdb_id = entry["pdb_id"]
            chain = entry["receptor_chain"]
            ligand = entry["ligand_id"]
            unique_id = f"{pdb_id}_{chain}_{ligand}"

            chunk_path = os.path.join(self.chunks_dir, f"{unique_id}.parquet")
            if os.path.exists(chunk_path) and not force:
                continue

            embeddings_path = os.path.join(self.embeddings_dir, f"{unique_id}.npy")
            if not os.path.exists(embeddings_path):
                # skip if embedding missing
                continue

            embeddings = np.load(embeddings_path)

            meta = pd.DataFrame(
                {
                    "pdb_id": pdb_id,
                    "receptor_chain": chain,
                    "ligand_id": ligand,
                    "position": np.arange(1, len(embeddings) + 1),
                }
            )

            esm_cols = pd.DataFrame(embeddings, columns=[f"esm_{i}" for i in range(embeddings.shape[1])])

            chunk_df = pd.concat([meta, esm_cols], axis=1)
            chunk_df.to_parquet(chunk_path, index=False)

            del embeddings, chunk_df, meta, esm_cols

        print("✅ All chunks saved")

    def load_embedding_df(self) -> pd.DataFrame:
        # pandas can read a folder of parquet files (pyarrow engine) as a dataset
        df = pd.read_parquet(self.chunks_dir)
        return df

    def merge(self, residue_df: pd.DataFrame, embedding_df: pd.DataFrame) -> pd.DataFrame:
        df_merge = residue_df.merge(
            embedding_df, on=["pdb_id", "receptor_chain", "ligand_id", "position"], how="inner"
        )
        return df_merge

    def save(self, df_merge: pd.DataFrame, path: str = "model_dataset.parquet"):
        df_merge.to_parquet(path, engine="pyarrow", compression="zstd")

    def run_all(self, raw_path: str = "BioLiP_nr.txt.gz", save_path: str = "model_dataset.parquet", force: bool = False):
        df = self.load_biolip(raw_path)
        df_cleaned = self.clean(df)
        residue_df = self.make_residue_df(df_cleaned)
        self.compute_embeddings(df_cleaned, force=force)
        self.chunk_embeddings(df_cleaned, force=force)
        embedding_df = self.load_embedding_df()
        df_merge = self.merge(residue_df, embedding_df)
        self.save(df_merge, save_path)
        return df_merge


# Example usage (Cell 1):
# Instantiate and run the full pipeline (this will compute embeddings on GPU if available)
# esm = ESM()
# df_merge = esm.run_all(raw_path="BioLiP_nr.txt.gz", save_path="model_dataset.parquet")