In [1]:
pip install ESM

Collecting ESM
  Using cached esm-3.2.1.post1-py3-none-any.whl.metadata (18 kB)
Collecting torch>=2.2.0 (from ESM)
  Downloading torch-2.11.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (29 kB)
Collecting torchvision (from ESM)
  Downloading torchvision-0.26.0-cp314-cp314-macosx_12_0_arm64.whl.metadata (5.5 kB)
Collecting torchtext (from ESM)
  Using cached torchtext-0.6.0-py3-none-any.whl.metadata (6.3 kB)
Collecting transformers<4.48.2 (from ESM)
  Using cached transformers-4.48.1-py3-none-any.whl.metadata (44 kB)
Requirement already satisfied: ipython in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ESM) (9.11.0)
Collecting einops (from ESM)
  Using cached einops-0.8.2-py3-none-any.whl.metadata (13 kB)
Collecting biotite>=1.0.0 (from ESM)
  Downloading biotite-1.6.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting msgpack-numpy (from ESM)
  Using cached msgpack_numpy-0.4.8-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting biopython (from ESM)
  Downloading biopython-1.86-cp314-cp314-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting scikit-learn (from ESM)
  Downloading scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl.metadata (11 kB)
Collecting brotli (from ESM)
  Downloading brotli-1.2.0-cp314-cp314-macosx_10_15_universal2.whl.metadata (6.1 kB)
Collecting attrs (from ESM)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: pandas in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ESM) (3.0.1)
Collecting cloudpathlib (from ESM)
  Using cached cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Collecting tenacity (from ESM)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting zstd (from ESM)
  Downloading zstd-1.5.7.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (29 kB)
Collecting filelock (from transformers<4.48.2->ESM)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting huggingface-hub<1.0,>=0.24.0 (from transformers<4.48.2->ESM)
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from transformers<4.48.2->ESM) (2.4.3)
Requirement already satisfied: packaging>=20.0 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from transformers<4.48.2->ESM) (26.0)
Collecting pyyaml>=5.1 (from transformers<4.48.2->ESM)
  Downloading pyyaml-6.0.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting regex!=2019.12.17 (from transformers<4.48.2->ESM)
  Downloading regex-2026.2.28-cp314-cp314-macosx_11_0_arm64.whl.metadata (40 kB)
Collecting requests (from transformers<4.48.2->ESM)
  Downloading requests-2.33.0-py3-none-any.whl.metadata (5.1 kB)
Collecting tokenizers<0.22,>=0.21 (from transformers<4.48.2->ESM)
  Using cached tokenizers-0.21.4-cp39-abi3-macosx_11_0_arm64.whl.metadata (6.7 kB)
Collecting safetensors>=0.4.1 (from transformers<4.48.2->ESM)
  Using cached safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl.metadata (4.1 kB)
Collecting tqdm>=4.27 (from transformers<4.48.2->ESM)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub<1.0,>=0.24.0->transformers<4.48.2->ESM)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.24.0->transformers<4.48.2->ESM)
  Using cached hf_xet-1.4.2-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.9 kB)
Collecting typing-extensions>=3.7.4.3 (from huggingface-hub<1.0,>=0.24.0->transformers<4.48.2->ESM)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting biotraj<2.0,>=1.0 (from biotite>=1.0.0->ESM)
  Downloading biotraj-1.2.2.tar.gz (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 1.1 MB/s  0:00:03 eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting msgpack>=0.5.6 (from biotite>=1.0.0->ESM)
  Downloading msgpack-1.1.2-cp314-cp314-macosx_11_0_arm64.whl.metadata (8.1 kB)
Collecting networkx>=2.0 (from biotite>=1.0.0->ESM)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting scipy>=1.13 (from biotraj<2.0,>=1.0->biotite>=1.0.0->ESM)
  Downloading scipy-1.17.1-cp314-cp314-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting charset_normalizer<4,>=2 (from requests->transformers<4.48.2->ESM)
  Downloading charset_normalizer-3.4.6-cp314-cp314-macosx_10_15_universal2.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests->transformers<4.48.2->ESM)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.26 (from requests->transformers<4.48.2->ESM)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests->transformers<4.48.2->ESM)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting setuptools<82 (from torch>=2.2.0->ESM)
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch>=2.2.0->ESM)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting jinja2 (from torch>=2.2.0->ESM)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=2.2.0->ESM)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: decorator>=5.1.0 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ipython->ESM) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ipython->ESM) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ipython->ESM) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ipython->ESM) (0.2.1)
Requirement already satisfied: pexpect>4.6 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ipython->ESM) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ipython->ESM) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ipython->ESM) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ipython->ESM) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from ipython->ESM) (5.14.3)
Requirement already satisfied: wcwidth in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ESM) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from jedi>=0.18.2->ipython->ESM) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from pexpect>4.6->ipython->ESM) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython->ESM) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython->ESM) (3.0.1)
Requirement already satisfied: pure_eval in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython->ESM) (0.2.3)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=2.2.0->ESM)
  Downloading markupsafe-3.0.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (2.7 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from pandas->ESM) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/austingilbride/miniconda3/envs/pdb_project/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas->ESM) (1.17.0)
Collecting joblib>=1.3.0 (from scikit-learn->ESM)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn->ESM)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting sentencepiece (from torchtext->ESM)
  Downloading sentencepiece-0.2.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (10 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision->ESM)
  Downloading pillow-12.1.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (8.8 kB)
Using cached esm-3.2.1.post1-py3-none-any.whl (2.4 MB)
Using cached transformers-4.48.1-py3-none-any.whl (9.7 MB)
Using cached huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
Using cached hf_xet-1.4.2-cp37-abi3-macosx_11_0_arm64.whl (3.6 MB)
Using cached tokenizers-0.21.4-cp39-abi3-macosx_11_0_arm64.whl (2.7 MB)
Downloading biotite-1.6.0-cp314-cp314-macosx_11_0_arm64.whl (41.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.5/41.5 MB 2.1 MB/s  0:00:19m0:00:0100:01m
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading msgpack-1.1.2-cp314-cp314-macosx_11_0_arm64.whl (84 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 2.5 MB/s  0:00:00 eta 0:00:01
Downloading pyyaml-6.0.3-cp314-cp314-macosx_11_0_arm64.whl (173 kB)
Downloading regex-2026.2.28-cp314-cp314-macosx_11_0_arm64.whl (289 kB)
Downloading requests-2.33.0-py3-none-any.whl (65 kB)
Downloading charset_normalizer-3.4.6-cp314-cp314-macosx_10_15_universal2.whl (294 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Using cached safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl (447 kB)
Downloading scipy-1.17.1-cp314-cp314-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 2.0 MB/s  0:00:10m0:00:0100:01m
Downloading torch-2.11.0-cp314-cp314-macosx_11_0_arm64.whl (80.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 MB 2.2 MB/s  0:00:35m0:00:0100:02
Downloading setuptools-81.0.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.7 MB/s  0:00:00 eta 0:00:01
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 3.0 MB/s  0:00:02 eta 0:00:01
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 3.7 MB/s  0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading biopython-1.86-cp314-cp314-macosx_11_0_arm64.whl (2.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 3.2 MB/s  0:00:00 eta 0:00:01
Downloading brotli-1.2.0-cp314-cp314-macosx_10_15_universal2.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.1/863.1 kB 1.9 MB/s  0:00:00 eta 0:00:01
Using cached cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
Using cached einops-0.8.2-py3-none-any.whl (65 kB)
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp314-cp314-macosx_11_0_arm64.whl (12 kB)
Using cached msgpack_numpy-0.4.8-py2.py3-none-any.whl (6.9 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 2.5 MB/s  0:00:03 eta 0:00:01
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Using cached torchtext-0.6.0-py3-none-any.whl (64 kB)
Downloading sentencepiece-0.2.1-cp314-cp314-macosx_11_0_arm64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 1.4 MB/s  0:00:00 eta 0:00:01
Downloading torchvision-0.26.0-cp314-cp314-macosx_12_0_arm64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 1.5 MB/s  0:00:01m0:00:0100:010m
Downloading pillow-12.1.1-cp314-cp314-macosx_11_0_arm64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 1.6 MB/s  0:00:02 eta 0:00:01
Downloading zstd-1.5.7.3-cp314-cp314-macosx_11_0_arm64.whl (230 kB)
Building wheels for collected packages: biotraj
  Building wheel for biotraj (pyproject.toml) ... done
  Created wheel for biotraj: filename=biotraj-1.2.2-cp314-cp314-macosx_11_0_arm64.whl size=851961 sha256=ecf2e56a7b7d856a46511aa1491e41ed0afb3e8b66ec8022aaa71dd0527c15e0
  Stored in directory: /Users/austingilbride/Library/Caches/pip/wheels/6c/0d/61/9f76c77cfe77e4c65671c9373739bace0ca3daed6000a808ab
Successfully built biotraj
Installing collected packages: zstd, mpmath, brotli, urllib3, typing-extensions, tqdm, threadpoolctl, tenacity, sympy, setuptools, sentencepiece, scipy, safetensors, regex, pyyaml, pillow, networkx, msgpack, MarkupSafe, joblib, idna, hf-xet, fsspec, filelock, einops, cloudpathlib, charset_normalizer, certifi, biopython, attrs, scikit-learn, requests, msgpack-numpy, jinja2, biotraj, torch, huggingface-hub, biotite, torchvision, torchtext, tokenizers, transformers, ESM
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43/43 [ESM][0m [ESM][0m [transformers]ub]er]
Successfully installed ESM-3.2.1.post1 MarkupSafe-3.0.3 attrs-26.1.0 biopython-1.86 biotite-1.6.0 biotraj-1.2.2 brotli-1.2.0 certifi-2026.2.25 charset_normalizer-3.4.6 cloudpathlib-0.23.0 einops-0.8.2 filelock-3.25.2 fsspec-2026.2.0 hf-xet-1.4.2 huggingface-hub-0.36.2 idna-3.11 jinja2-3.1.6 joblib-1.5.3 mpmath-1.3.0 msgpack-1.1.2 msgpack-numpy-0.4.8 networkx-3.6.1 pillow-12.1.1 pyyaml-6.0.3 regex-2026.2.28 requests-2.33.0 safetensors-0.7.0 scikit-learn-1.8.0 scipy-1.17.1 sentencepiece-0.2.1 setuptools-81.0.0 sympy-1.14.0 tenacity-9.1.4 threadpoolctl-3.6.0 tokenizers-0.21.4 torch-2.11.0 torchtext-0.6.0 torchvision-0.26.0 tqdm-4.67.3 transformers-4.48.1 typing-extensions-4.15.0 urllib3-2.6.3 zstd-1.5.7.3
Note: you may need to restart the kernel to use updated packages.

In [21]:
import os
import numpy as np
import pandas as pd

class PDBparser:
    
    def __init__(self, pdbPath):
        self.__pdbPath = pdbPath

    def get_residues(self):
        with open(self.__pdbPath, 'r') as file:
            aa_map = {
                'ALA': 'A', 'ARG': 'R', 'ASN': 'N', 'ASP': 'D',
                'CYS': 'C', 'GLN': 'Q', 'GLU': 'E', 'GLY': 'G',
                'HIS': 'H', 'ILE': 'I', 'LEU': 'L', 'LYS': 'K',
                'MET': 'M', 'PHE': 'F', 'PRO': 'P', 'SER': 'S',
                'THR': 'T', 'TRP': 'W', 'TYR': 'Y', 'VAL': 'V'}
            
            seen_residues = {}

            for line in file:
                line = line.strip()

                if line.startswith('ATOM'):
                    res_name = line[17:20]
                    chain = line[21]
                    res_num = int(line[22:26])

                    if chain not in seen_residues:
                        seen_residues[chain] = {}

                    if res_num not in seen_residues[chain]:
                        seen_residues[chain][res_num] = aa_map.get(res_name, 'err')
            
            sequences = {}
            for chain, residues in seen_residues.items():
                sequences[chain] = "".join(residues[num] for num in sorted(residues))     

        df = pd.DataFrame(
            list(sequences.items()),
            columns=['chain', 'sequence']
        )

        return df


pdb = PDBparser("/Users/austingilbride/masters_sem_2/SBI/Predicting_Binding_Sites/1CY1.pdb")
pdb_parsed = pdb.get_residues()
pdb_parsed.head()

  chain                                           sequence
0     A  GKALVIVESPAKAKTINKYLGSDYVVKSSVGHIRDLPRGALVNRMG...

In [ ]:
'''#Input should be sequence in string format, output should be df with pdb_id, chain_id, residue, and n_esm embeddings columns
from esm.models.esmc import ESMC
from esm.sdk.api import ESMProtein, LogitsConfig
import torch

class ESM_df:
    """Apply ESM model to get protein embeddings in df format from a PDB sequence
    Methods:
        get_embeddings == gets us the embeddings from the ESM of a PDB file 
    """

    def __init__(self, pdb_object):
        self.pdb_object = pdb_object
        
    def get_embeddings(self, pdb_object):
        client = ESMC.from_pretrained("esmc_300m")
        os.makedirs("embeddings_proteins2", exist_ok=True)
        dictionary = {}
        for _, row in self.pdb_object.iterrows():
            chain = row["chain"]
            sequence_full = str(row["sequence"])

            protein = ESMProtein(sequence=sequence_full)
            protein_tensor = client.encode(protein)
            
            with torch.no_grad():
                output = client.logits(
                protein_tensor,
                LogitsConfig(sequence=True, return_embeddings=True)
                )      
            embeddings = output.embeddings.squeeze(0).half().cpu().numpy()[1:-1, :]
            dictionary[chain] = embeddings
        

        
        output = pd.DataFrame.from_dict(dictionary, orient="index", columns=["embeddings"])
        output = output.reset_index().rename(columns={'index': "chain"})
        return output
'''

In [ ]:
import os
import pandas as pd
import torch
from esm.models.esmc import ESMC
from esm.sdk.api import ESMProtein, LogitsConfig

class ESM_df:

    def __init__(self, pdb_df, pdb_id=None):
        self.pdb_df = pdb_df
        self.pdb_id = pdb_id

    def get_embeddings(self):
        client = ESMC.from_pretrained("esmc_300m")
        os.makedirs("embeddings_proteins2", exist_ok=True)

        all_rows = []

        for _, row in self.pdb_df.iterrows():
            chain_id = row["chain"]
            sequence_full = str(row["sequence"])
            residue_list = list(sequence_full)

            protein = ESMProtein(sequence=sequence_full)
            protein_tensor = client.encode(protein)

            with torch.no_grad():
                output = client.logits(
                    protein_tensor,
                    LogitsConfig(sequence=True, return_embeddings=True)
                )

            
            embeddings = output.embeddings.squeeze(0).cpu().numpy()[1:-1, :]

            # safety check from chat, developed while debugging. 
            if embeddings.shape[0] != len(residue_list):
                raise ValueError(
                    f"Mismatch for chain {chain_id}: "
                    f"{embeddings.shape[0]} embeddings vs {len(residue_list)} residues"
                )

            emb_cols = [f"emb_{i}" for i in range(embeddings.shape[1])]
            chain_df = pd.DataFrame(embeddings, columns=emb_cols)

            chain_df.insert(0, "residue", residue_list)
            chain_df.insert(0, "chain_id", chain_id)
            chain_df.insert(0, "pdb_id", self.pdb_id)

            all_rows.append(chain_df)

        final_df = pd.concat(all_rows, ignore_index=True)
        return final_df

In [26]:
embeddings = ESM_df(pdb_parsed, "1CY1")
df_with_embeddings = embeddings.get_embeddings()

df_with_embeddings.head()

,pdb_id,chain_id,residue,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_950,emb_951,emb_952,emb_953,emb_954,emb_955,emb_956,emb_957,emb_958,emb_959
0,1CY1,A,G,-0.006309,-0.040782,0.018655,-0.010588,0.008218,0.037279,-0.004148,...,0.030521,0.002574,0.026207,0.048397,0.024329,0.004088,-0.012002,0.034533,0.043613,0.060083
1,1CY1,A,K,0.000097,0.015087,-0.025818,-0.028518,-0.041529,0.019195,-0.004833,...,0.012599,-0.026920,-0.054776,0.057457,-0.003940,0.043067,-0.021521,0.061916,0.035811,0.018635
2,1CY1,A,A,0.048292,0.014519,-0.041627,-0.027983,0.010406,0.026925,-0.017442,...,-0.036829,-0.005102,0.042052,0.001421,0.010493,-0.043738,-0.031952,0.007599,0.002892,-0.013188
3,1CY1,A,L,-0.001959,-0.111996,0.022011,-0.004863,0.011412,0.017976,-0.026455,...,-0.053971,-0.034352,-0.018874,-0.041282,0.020682,-0.011068,0.071930,0.016299,0.001028,-0.036806
4,1CY1,A,V,0.019288,-0.033036,-0.023495,-0.070523,-0.027506,-0.006572,-0.025732,...,0.025228,-0.015312,-0.002438,-0.031381,-0.036912,-0.022695,0.015744,-0.025004,0.025090,-0.051024